name: Build and Deploy

on:
  push:
    branches:
      - assignment31
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Deploy to Heroku
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "rvleeuwendevops31coursepage"
          heroku_email: "richard@leeuwenmail.com"
